### ISSUE TITLE
EGO Example should show convergence

### ISSUE THREAD

**Issue by sanaaZ** [openturns/openturns#1302] opened 2019-10-28 13:42 UTC
i tried to run the code embeded in http://openturns.github.io/openturns/latest/user_manual/_generated/openturns.EfficientGlobalOptimization.html?highlight=ego

the code runs just well but the optimum reached by OT is incorrect and result.getIterationNumber() returns 0

i work with the version 1.13 on a windows 10 computer

regards,

**Comment by jschueller** [comment] 2019-10-28 13:53
- the minimum returned is -610 at [-5,-5,-5,-5], how is that incorrect ?

- currently EGO is not driven by the iteration number but the evaluation number, so the iteration number is just not set and it returns the default value of 0, but actually here the number of iteration is also the number of evaluation so I guess we could also set it

**Comment by sanaaZ** [comment] 2019-10-28 14:15
Sorry, i meant to refer to http://openturns.github.io/openturns/latest/examples/ego.html?highlight=ego
I tried OT's EGO on the ackley function (but without the nlopt optimization part) and the returned value is 4.2 (instead of 0) with the objective funtion being evaluated only once.

I tried to increase the maximumEvaluationNumber and the maximumIterationNumber unsuccessfully 

thank you for your help!

**Comment by jschueller** [comment] 2019-10-28 14:25
I've got 5 iterations, with the optimum 4.2  (at [0.5, 0.5]) too
The nlopt refinement step make it go to 0.0
Maybe you're looking for a more relevant example ?

**Comment by sanaaZ** [comment] 2019-10-28 14:41
when i run the example the optimum is found within only one evaluation of the objective function. I guess that what was quite confusing is that all my runs have stopped after only one iteration / evaluation.
however i've just tried changing the ImprovementFactor to a smaller value and it seems to be forcing the algorithm  to do a bit more exploring. this tweak also helped the EGO algorithm optimizing my user defined function.

I don't know if it's a good idea but maybe a SetIterationsNumber() method could be added to the EGO algorithm?

anyways, thank you for your help, and yes i think that an example exhibiting full convergence to the analytical optimum would be most welcome in the OT documentation :)

regards
Sanaa

**Comment by mbaudin47** [comment] 2019-11-04 09:37
* getIterationNumber() should be fixed, as mentionned by @jschueller 
* The example has several formatting issues. The bib reference is wrong. The equations are wrongly formatted, with wrong parentheses, wrong exponent for the interval [-15,15^d], etc...
* The example does not show the progress of the algorithm. A graphics would be useful :

![TRM-Branin](https://user-images.githubusercontent.com/31351465/68111156-c9a1b380-feee-11e9-85bd-ca8854709f86.png)

* The example should be split into several ones, given that the feature is massive: the quantity of code should be reflected by the quantity of examples.

* The example does not show the convergence to the optimum, as @sanaaZ said.

**Comment by jschueller** [comment] 2020-04-03 16:21
I fixed the typos in #1422

**Comment by josephmure** [comment] 2021-01-12 22:57
@sanaaZ or @jschueller Given the remaining issue concerns the doc exclusively, I think this ticket should be renamed "Example should show how EGO converges to the optimum" or something like that.

**Comment by jschueller** [comment] 2021-01-13 08:07
ok

**Comment by mbaudin47** [comment] 2021-01-15 21:59
The colormap might be created based on Matplotlib's pcolor. An example is given at:

https://stackoverflow.com/questions/59330497/how-to-interpolate-2d-spatial-data-with-kriging-in-python

Meanwhile, I created an example of the Branin test case at:

http://openturns.github.io/openturns/master/auto_numerical_methods/optimization/plot_ego.html

However, example can always be improved, or a new one be created.

**Comment by mbaudin47** [comment] 2024-09-06 09:31
I agree that the API was fixed so that the number of iterations is now consistently evaluated. I do not agree to close the issue because there is still a remaining problem with this example, as pointed out by @sanaaZ. The issue is that the EGO algorithm does not converge very rapidly in this case. In order to increase the accuracy of the result, we have to increase the number of iterations. Now the problem is that the Notebook is very long, which is a problem because we want to limit the elapsed of a single example.

The example is, furthermore, ambiguous in the sense that it makes us think that EGO performs quite accurately, which is wrong. The figure below uses the same parameters but shows the exact optimal function value: we see that the minimum is not reached.

![image](https://github.com/user-attachments/assets/9970c467-1f2a-4747-823a-9b426005ffdf)

**Figure 1.** The function value depending on the iteration number for the EGO algorithm applied on the Ackley example with the parameters used in the example.

In order to get more accurate results, we can increase the maximum number of iterations up to 50, as presented in the next figure.

![image](https://github.com/user-attachments/assets/294c1375-eb2d-43b4-84a4-7fcf502a7555)

**Figure 2.** The function value depending on the iteration number for the EGO algorithm applied on the Ackley example with 50 iterations.

The problem is now that the Notebook is longer. The next cell shows the result of the `run()` method of the EGO algorithm. We see that it needs more than 2 seconds.

![image](https://github.com/user-attachments/assets/605f6c2b-bfff-4cfc-8ed0-3b1c82f19251)

**Figure 3.** The elapsed time of the EGO algorithm with 50 iterations can take up to 2 seconds on my workstation.

In order to solve the issue, we need to find a method to improve the speed, while maintaining a good accuracy. This may require to improve the way EGO updates the kriging hyperpermeters. Unfortunately, I was not able to fix this.

**Comment by m-balesdent** [comment] 2024-09-06 09:34
OK, I will try several tunings of EGO to make it faster on this test case.

**Comment by m-balesdent** [comment] 2024-09-06 09:50
@mbaudin47 With changing the covariance model (to a Matern one), I found this curve for the Ackley example with the same computational budget  : 

![Figure_3](https://github.com/user-attachments/assets/da085658-8f52-44a9-905e-b31ee9651077)

It that okay with you?

**Closed** 2024-10-02 13:55 UTC
Labels: doc
