### ISSUE TITLE
The doc of PlotDesign has no figure

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1070] opened 2019-04-06 12:35 UTC
The doc of PlotDesign has no figure. This is a pity, given the graphical purpose of this function. Since the implementation is based on Python, I do not know how to insert a figure in the help page. This is why I suggest this notebook.

[Demo of PlotDesign.zip](https://github.com/openturns/openturns/files/3050451/Demo.of.PlotDesign.zip)

**Comment by sofianehaddad** [comment] 2020-04-24 08:20
duplicate of #1375

**Closed by sofianehaddad** 2020-04-24 08:20 UTC
Labels: doc
