### ISSUE TITLE
Boundary Correction in Kernelsmoothing

### ISSUE THREAD

**Issue by adutfoy** [openturns/openturns#2302] opened 2023-05-10 15:57 UTC
Hello,

It seems that the 0.0 value for the lower bound in the boundary correction of the kernel smoothing is a problem...
```from openturns import *
from openturns.viewer import View

sample = Normal(10, 0.1).getSample(100)
kernel = KernelSmoothing()
kernel.setBoundingOption(KernelSmoothing.LOWER)

# no pb here
kernel.setLowerBound(0.0010)
View(kernel.build(sample).drawPDF()).show()

# pb here
kernel.setLowerBound(0.0)
View(kernel.build(sample).drawPDF()).show()

```

**Comment by regislebrun** [comment] 2023-05-10 17:10
Duplicate of  #2238

**Closed by regislebrun** 2023-05-10 17:10 UTC
