### ISSUE TITLE
Kriging: explainable behaviour? 

### ISSUE THREAD

**Issue by mathieu-couplet** [openturns/openturns#1339] opened 2019-12-05 13:30 UTC
Hello.

In the following example, I expected to get the same result with the two KrigingAlgorithms since they share the same basis, covariance function, observations and noise amplitude, however I did not (difference in trend).

What did I miss, please ?

Thank you.

```
import openturns as ot

# data
q, p, n = 3, 1, 1000
x = ot.Normal(q).getSample(n)
G = ot.SymbolicFunction(['x0', 'x1', 'x2'], ['x0 + x1 + x2'])
y = G(x)

# first kriging
basis = ot.ConstantBasisFactory(q).build()
covarianceModel = ot.MaternModel([0.5]*q, 2.5)
noise_amplitude = 1.0E-5
algo = ot.KrigingAlgorithm(x, y, covarianceModel, basis)
algo.setOptimizeParameters(True)
algo.setNoise(ot.Point(n, noise_amplitude))
algo.run()
res = algo.getResult()
covarianceModel = res.getCovarianceModel()
print("res1 = ", res.getTrendCoefficients(), covarianceModel)

# second kriging
algo = ot.KrigingAlgorithm(x, y, covarianceModel, basis)
algo.setOptimizeParameters(False)
algo.setNoise(ot.Point(n, noise_amplitude))
algo.run()
res = algo.getResult()
print("res2 = ", res.getTrendCoefficients(), res.getCovarianceModel())

```

**Comment by sofianehaddad** [comment] 2019-12-08 23:18
Looks strange. It is mainly due to the `setNoise` but I do not know why exactly (without `setNoise` the trend coefficients are the same)

Note also (in this case) that replacing the `setNoise` In the second algorithm by a `covarianceModel.setNuggetFactor` provides similar results :

```
# second kriging
eps = covarianceModel.getNuggetFactor()
covarianceModel.setNuggetFactor(1e-5 + eps)
algo = ot.KrigingAlgorithm(x, y, covarianceModel, basis)
algo.setOptimizeParameters(False)
algo.run()
res = algo.getResult()
print("res2 = ", res.getTrendCoefficients(), res.getCovarianceModel())
```

**Comment by mathieu-couplet** [comment] 2019-12-09 12:25
I am surprised that the nugget factor was not set to zero when the MaternModel is created. I though the nugget factor should be seen has a modelling parameter (potentially optimized), not a numerical one. Moreover the GeneralLinearModelAlgorithm (with LAPACK: computeLapackLogDeterminantCholesky) has already a mechanism to add some artificial noise when it is necessary.
However it is true that this artificial noise is not always great enough in the sense that a larger one may provide a better metamodel. My initial goal was to tune such "numerical hyperparameters" to get the best metamodel over a test set potentially in distinguishing the artificial noise injected during the optimization of the (reduced) likelihood from the artificial noise taken into account when conditioning the gaussian process.

Regards,
Mathieu.

**Comment by sofianehaddad** [comment] 2019-12-12 14:08
Hi @mathieu-couplet the issue is not directly related to the nugget factor but in this specific case we use it to "solve" the problem.
In fact to get the same results, instead of using the `setNuggetFactor`, we can replace the covariance model with a "correlation" model :
```
correlation_model = ot.CovarianceModel(covarianceModel)
correlation_model.setAmplitude([1])
algo = ot.KrigingAlgorithm(x, y, correlation_model, basis)
algo.setNoise(ot.Point(n, noise_amplitude))
algo.setOptimizeParameters(False)
algo.run()
res = algo.getResult()
print("res2 = ", res.getTrendCoefficients(), res.getCovarianceModel())
```

**Comment by sofianehaddad** [comment] 2020-04-20 13:57
Fixed in https://github.com/openturns/openturns/pull/1379

**Closed by sofianehaddad** 2020-04-20 13:57 UTC
