### ISSUE TITLE
Examples of functions with discrete inputs

### ISSUE THREAD

**Issue by adutfoy** [openturns/openturns#1323] opened 2019-11-14 18:28 UTC
Iluustrate functions which some inputs are discrete: use the 'if' command or declare it as the indice of a table.
Give elements on the consequences of the choice on the evaluation of a gradient.

**Comment by mbaudin47** [comment] 2019-11-18 14:58
This is a duplicate of #1318. (sorry for creating the issue twice)

**Closed** 2019-11-18 15:02 UTC
