### ISSUE TITLE
KarhunenLoeveSVDAlgorithm can fail

### ISSUE THREAD

**Issue by mbaudin47** [openturns/openturns#1505] opened 2020-05-26 09:51 UTC
Consider the time series sample from the file timeseries-bug-simplified.txt. It contains the observed physical measure during 95 weeks on a regular time grid with 95 time steps. Each column of the file corresponds to a week and each row corresponds to a date. On this dataset, I perform the Karhunen-Loève decomposition with `KarhunenLoeveSVDAlgorithm`. This produces a LAPACK error with the DGESDD function:

http://www.netlib.org/lapack/explore-html/d1/d7e/group__double_g_esing_gad8e0f1c83a78d3d4858eaaa88a1c5ab1.html

The error is related to the value of the parameter number 12, which seems to be LWORK. 

To reproduce the bug, consider the following script:
```
import openturns as ot

sample = ot.Sample_ImportFromCSVFile("timeseries-bug-simplified.txt")

timesNumber = sample.getSize()

times = ot.Sample(range(timesNumber), 1)
timeInterval = ot.Interval(0.0, timesNumber - 1.0)

numberOfIntervals = timesNumber - 1
mesher = ot.IntervalMesher([numberOfIntervals])
mesh = mesher.build(timeInterval)

sampleSize = sample.getDimension()
processSample = ot.ProcessSample(mesh, sampleSize, 1)
for i in range(sampleSize):
    values = sample[:, i]
    processSample[i] = ot.Field(mesh, values)

threshold = 1.e-4
algo = ot.KarhunenLoeveSVDAlgorithm(processSample, threshold)
algo.run()
KLResult = algo.getResult()
scaledModes = KLResult.getScaledModesAsProcessSample()
nbModes = scaledModes.getSize()
print("    nbModes=", nbModes)
```
with the following file:

[timeseries-bug-simplified.txt](https://github.com/openturns/openturns/files/4681282/timeseries-bug-simplified.txt)

This produces the error:
```
 ** On entry to DGESDD parameter number 12 had an illegal value
```

This bug can be reproduced with Linux (but not Windows), with Python3.7 on OT 1.14. The file timeseries-bug-simplified.txt is expected to be the smallest file which reproduces the error (I removed unnecessary trailing columns and rows to get it). It can be reproduced with a larger file which has more columns, i.e. more time series with the same time grid.

**Comment by jschueller** [comment] 2020-05-26 09:58
I cant reproduce, what's your lapack version ?

**Comment by mbaudin47** [comment] 2020-05-26 20:47
```
$ python
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.show_config()
blas_mkl_info:
    libraries = ['blas', 'cblas', 'lapack', 'pthread', 'blas', 'cblas', 'lapack']
    library_dirs = ['/home/osboxes/miniconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/osboxes/miniconda3/include']
blas_opt_info:
    libraries = ['blas', 'cblas', 'lapack', 'pthread', 'blas', 'cblas', 'lapack', 'blas', 'cblas', 'lapack']
    library_dirs = ['/home/osboxes/miniconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/osboxes/miniconda3/include']
lapack_mkl_info:
    libraries = ['blas', 'cblas', 'lapack', 'pthread', 'blas', 'cblas', 'lapack']
    library_dirs = ['/home/osboxes/miniconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/osboxes/miniconda3/include']
lapack_opt_info:
    libraries = ['blas', 'cblas', 'lapack', 'pthread', 'blas', 'cblas', 'lapack', 'blas', 'cblas', 'lapack']
    library_dirs = ['/home/osboxes/miniconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/osboxes/miniconda3/include']
```

**Comment by sofianehaddad** [comment] 2020-05-28 07:29
Can not reproduce. @mbaudin47 `np.show_config` is specific to `numpy`. 
How did you install OT? A conda install or from sources? In that case, what is the Blas used (openblas? )

**Comment by mbaudin47** [comment] 2020-05-28 17:33
None! This installation is from pip in environment A (based on a Docker image in gitlab) and miniconda with pip packages on environment B (an Ubuntu system within a virtual machine). I guess that is the reason why you both cannot reproduce the issue.

**Comment by jschueller** [comment] 2020-05-28 18:08
I can reproduce with 1.14, but not with 1.15 as we up switched from manylinux1 to manylinux2010 pypa images (el6->el6 which must bring newer blas). closing.

**Closed by jschueller** 2020-05-28 18:08 UTC

**Comment by mbaudin47** [comment] 2020-05-29 21:12
Thank your very much. This is good to know.
