### ISSUE TITLE
OpenTurns  FittingTest_BestModelKolmogorov() method issues

### ISSUE THREAD

**Issue by swimhiking** [openturns/openturns#1186] opened 2019-07-15 04:31 UTC
Hi there,

I have a task which use a compound distribution simulate 1 million samples, then feed these simulated data to do a complex computation, then using  ot.FittingTest.BestModelKolmogorov try to find a best fitted distribution from the above calculated results sample, I found OpenTurns 1.10 is a best version to do this task, if I try using 1.12 or 1.13, then I will got lots of p value = 0, this means I cannot find a fitted distribution. Not sure anyone find this issues? 
Thanks.

**Comment by sofianehaddad** [comment] 2019-07-15 06:48
First consider the general remarks:

 - 1 item/issue only in an opened GitHub issue

 - Please provide if possible a small script that we could reproduce  + environment (openturns version, os, implementation (condo, build, ...)

By the way I start answering for the first item.

The `BestModelKolmogorov` slightly changed since 1.10
From a mathematical point of view, the oldest way of applying the test is wrong as we should include the fact that `true` parameters are unknown. Indeed  with `estimated parameters` from a sample, statistic is usually `small` because the parameters of the distribution have been computed from the sample. If you want to retrieve your results you should first estimate the distribution and then feed the `BestModelKolmogorov` with your `data` and `estimated distribution`.
Note also that with large dataset, we often reject null hypothesis and found p-values around 0

For the second item, the reason it fails since `1.12` is linked to the support : I will have a look

**Comment by jschueller** [comment] 2019-07-22 08:21
For the truncatednormal part:
Normal::computeProbability (and the computeProbability methods) uses ```if (interval.isNumericallyEmpty()) return 0.0;```
and Interval::isNumericallyEmpty uses a fixed value: Domain-SmallVolume=1e-12,
so if the range is <1e-12 computeProbability is always 0.

**Comment by jschueller** [comment] 2019-07-22 08:24
@swimhiking moved the truncatednormal bug to #1190

**Comment by mbaudin47** [comment] 2019-09-10 18:39
I guess that this issue is related to #1217. 

@swimhiking : if you set 
```
ot.ResourceMap.SetAsUnsignedInteger("FittingTest-KolmogorovSamplingSize",1000)
```
prior to the call to `BestModelKolmogorov` does your script works fine ? If yes, then this issue is an duplicate of #1217.

**Comment by mbaudin47** [comment] 2019-09-25 20:32
This issue is really a duplicate of #1217, this is why I would close the current issue, if I could.

**Comment by sofianehaddad** [comment] 2019-09-26 12:31
@mbaudin47 not exactly.
The #1217 deals with performance whereas here it is about a behaviour. Even if the two tickets (three infant if we include #1061 ) are due to the "new" feature of the fitting test

**Comment by mbaudin47** [comment] 2021-01-14 15:02
@swimhiking : I guess that OT1.16 fixes your issue, isn'it? This is because you can now use `Lilliefors` class, which performance have been greatly improved.

**Comment by jschueller** [comment] 2021-01-14 15:09
yes, reopen if needed

**Closed by jschueller** 2021-01-14 15:09 UTC
Labels: help wanted

**Comment by swimhiking** [comment] 2021-01-14 15:34
Thank you Michael, I will update to  version1.16.
