### ISSUE TITLE
Non-cyclic contour hue

### ISSUE THREAD

**Issue by jschueller** [openturns/openturns#2626] opened 2024-04-26 06:20 UTC
### What happened?

An idea mentioned by Regis to improve readability of contour plots was to avoid purple colors

![contour2](https://github.com/openturns/openturns/assets/3832365/b23ad3ec-9ba7-4794-8911-071411026ff6)
![contour1](https://github.com/openturns/openturns/assets/3832365/923a7278-381c-44fb-b586-f6f0cdb5ef49)

But this clashes with #2587

### How to reproduce the issue?

```shell
diff --git a/lib/src/Base/Func/EvaluationImplementation.cxx b/lib/src/Base/Func/EvaluationImplementation.cxx
index a56d7f823..5d6437c9b 100644
--- a/lib/src/Base/Func/EvaluationImplementation.cxx
+++ b/lib/src/Base/Func/EvaluationImplementation.cxx
@@ -447,7 +447,7 @@ Graph EvaluationImplementation::draw(const UnsignedInteger firstInputMarginal,
     current.setLabels(Description(1, labels[i]));
     current.setDrawLabels(false);
     current.setLegend(labels[i]);
-    current.setColor(Contour::ConvertFromHSV((360.0 * i / levels.getDimension()), 1.0, 1.0));
+    current.setColor(Contour::ConvertFromHSV((270.0 * i / levels.getDimension()), 1.0, 1.0));
     graph.add(current);
   }
   return graph;
diff --git a/lib/src/Base/Stat/CovarianceModelImplementation.cxx b/lib/src/Base/Stat/CovarianceModelImplementation.cxx
index 96f26e59c..f153e4c8f 100644
--- a/lib/src/Base/Stat/CovarianceModelImplementation.cxx
+++ b/lib/src/Base/Stat/CovarianceModelImplementation.cxx
@@ -1277,7 +1277,7 @@ Graph CovarianceModelImplementation::draw(const UnsignedInteger rowIndex,
     current.setLabels(Description(1, labels[i]));
     current.setDrawLabels(false);
     current.setLegend(labels[i]);
-    current.setColor(Contour::ConvertFromHSV((360.0 * i / levels.getDimension()), 1.0, 1.0));
+    current.setColor(Contour::ConvertFromHSV((270.0 * i / levels.getDimension()), 1.0, 1.0));
     graph.add(current);
   }
   return graph;
```

**Comment by regislebrun** [comment] 2024-04-26 21:25
@jschueller In the HSV color space the hue is divided into 6 sectors bounded by the primary and complementary colors. The idea I had was to remove the last sector, so 360.0 should be replaced by 300.0 and not 270.0.
I checked it on the NormalGamma PDF and it looks good to me. The last color is violet, quite far away from red

![Figure_1](https://github.com/openturns/openturns/assets/8220933/44c298c8-aa65-4e21-8e83-5a1c993457ec)

**Comment by mbaudin47** [comment] 2024-06-16 21:11
The problem is that the red color is both the highest and the lowest color in the color map. Here is, for example, the result of `drawPDF()` from a bi-dimensional Gaussian.
```
#%%
import openturns as ot
import numpy as np

print(ot.__version__)

# %%
numberOfLevels = 5
ot.ResourceMap.SetAsUnsignedInteger("Contour-DefaultLevelsNumber", numberOfLevels)

# %%
graph = ot.Normal(2).drawPDF()
graph
```

![image](https://github.com/openturns/openturns/assets/31351465/e9459f94-8682-4101-8c05-96562f3c3b26)

We see that the yellow line is surrounded by red lines, which is quite surprising.

**Comment by josephmure** [comment] 2024-06-17 08:48
I vote to close the issue. We simply need to stop using the HSV color map.

**Comment by mbaudin47** [comment] 2024-06-17 19:10
I agree. Here is the result by setting "viridis" in the default color map of a contour.
```python
ot.ResourceMap.SetAsString("Contour-DefaultColorMap", "viridis")
graph = ot.Normal(2).drawPDF()
contour = graph.getDrawable(0).getImplementation()
contour.setColorMap("viridis")
graph.setDrawable(contour, 0)
```
![image](https://github.com/openturns/openturns/assets/31351465/f646a823-c44b-413b-a744-b041d4ce38a2)
**Figure 1.** The iso-values of a Gaussian distribution with Viridis colormap.

**Comment by regislebrun** [comment] 2024-06-17 21:00
@josephmure I fully disagree with you. The HSV colormap, if used correctly, provides useful information. The fact that it is proposed e.g by paraview is an indication of its usefulness.

**Comment by josephmure** [comment] 2024-09-04 08:18
To be discussed further during a technical committee meeting

**Comment by josephmure** [comment] 2024-10-14 12:54
ParaView new default: https://www.kitware.com/new-default-colormap-and-background-in-next-paraview-release/

**Comment by mbaudin47** [comment] 2024-10-14 14:04
"coolwarm" is also available in Matplotlib, see https://matplotlib.org/stable/users/explain/colors/colormaps.html : 

![image](https://github.com/user-attachments/assets/53cd282b-5a6b-4f1d-8e2d-5284aa483539)

**Closed** 2024-10-21 11:54 UTC
Labels: question, graph
